name: Increment Version and Tag

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tag_version:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Increment version and tag
        id: increment_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ ! -f version.txt ]; then
            echo "version.txt not found!"
            exit 1
          fi
          
          version=$(cat version.txt)
          if [[ ! $version =~ ^[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version format in version.txt. Expected MAJOR.MINOR."
            exit 1
          fi
          
          major_minor=$version
          echo "HERE ARE THE TAGS"
          echo "$(git tag -l "${major_minor}.*")"
          latest_patch=$(git tag -l "${major_minor}.*" | grep -oE "[0-9]+$" | sort -n | tail -1)
          if [ -z "$latest_patch" ]; then
            latest_patch=0
          fi
          
          new_patch=$((latest_patch + 1))
          new_version="${major_minor}.${new_patch}"
          
          git tag $new_version
          git push origin $new_version

          echo $new_version > version.txt

      - name: Upload version.txt as artifact
        uses: actions/upload-artifact@v3
        with:
          name: version.txt
          path: version.txt

