name: Increment Version and Tag

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tag_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Read version from version.txt
        id: read_version
        run: |
          if [ ! -f version.txt ]; then
            echo "version.txt not found!"
            exit 1
          fi
          version=$(cat version.txt)
          if [[ ! $version =~ ^[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version format in version.txt. Expected MAJOR.MINOR."
            exit 1
          fi
          echo "::set-output name=major_minor::$version"

      - name: Get latest patch version
        id: get_latest_patch
        run: |
          major_minor=${{ steps.read_version.outputs.major_minor }}
          latest_patch=$(git tag -l "${major_minor}.*" | grep -oE "[0-9]+$" | sort -n | tail -1)
          if [ -z "$latest_patch" ]; then
            latest_patch=0
          fi
          new_patch=$((latest_patch + 1))
          new_version="${major_minor}.${new_patch}"
          echo "::set-output name=new_version::$new_version"

      - name: Create and push new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          new_version=${{ steps.get_latest_patch.outputs.new_version }}
          git tag $new_version
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} $new_version

